environment:
  VisualStudioVersion: 14.0

version: 0.1.0-CI{build}
  
shallow_clone: true
  
# Disable tests
test: off

#artifacts:
#  - path: NuGet\*.nupkg
#    name: nupkgfiles

# Publish to myget.org feed
#deploy:
#  provider: NuGet
#  server: https://www.myget.org/F/dserfozo/
#  api_key:
#    secure: uz70X1rDufUiuaV59aw5GKHF6lLvRCe9QkBZQkjGaxwAP/LSuVHdRAdEwRIZhkai
#  skip_symbols: true
#  artifact: nupkgfiles